spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


ml.service.url=http://localhost:8001/recommend/
#ml.service.url=https://recommendml-production.up.railway.app/recommend/